name: Deploy documentation
on:
  push:
    branches: ['master']
    paths: ['docs/**']
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install npm dependencies
        run: cd docs && npm install
      - name: Build VuePress documentation
        run: cd docs && npm run docs:build
      - name: Deploy 🚀to GitHub pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
